Repository The-Aether-Team/The-Aether, pull requests merged in 2022-01, with the labels that each got.

#320 refactor: Adjustments to a couple more classes.
  src/main/java/com/gildedgames/aether/core/data/AetherWorldData.java
  src/main/java/com/gildedgames/aether/core/data/provider/AetherWorldProvider.java
  src/main/java/com/gildedgames/aether/core/util/BlockLogic.java
  src/main/java/com/gildedgames/aether/core/util/BlockPlacers.java
Labels: status/pending-review

#309 RenderFixed: Sheepuff and Skyroot Bed
  src/main/java/com/gildedgames/aether/client/renderer/entity/model/SheepuffModel.java
  src/main/java/com/gildedgames/aether/common/block/utility/SkyrootBedBlock.java
  src/main/java/com/gildedgames/aether/common/item/block/SkyrootBedItem.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
Labels: version/1.18

#337 Feat: Adding swets.
  src/generated/resources/.cache/cache
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/assets/aether/models/item/swet_spawn_egg.json
  src/generated/resources/data/aether/loot_tables/entities/swet.json
  src/generated/resources/data/aether/loot_tables/entities/swet/blue.json
  src/generated/resources/data/aether/loot_tables/entities/swet/gold.json
  src/main/java/com/gildedgames/aether/client/registry/AetherRenderers.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/SwetRenderer.java
  src/main/java/com/gildedgames/aether/common/entity/monster/SwetEntity.java
  src/main/java/com/gildedgames/aether/common/entity/passive/MountableEntity.java
  src/main/java/com/gildedgames/aether/common/registry/AetherEntityTypes.java
  src/main/java/com/gildedgames/aether/common/registry/AetherItems.java
  src/main/java/com/gildedgames/aether/common/registry/AetherLoot.java
  src/main/java/com/gildedgames/aether/core/data/AetherItemModelData.java
  src/main/java/com/gildedgames/aether/core/data/AetherLangData.java
  src/main/java/com/gildedgames/aether/core/data/AetherLootTableData.java
Labels: feat/entity, version/1.18

#377 feat & fix: Mineable Tags for Aether Blocks
  src/generated/resources/.cache/cache
  src/generated/resources/data/minecraft/tags/blocks/mineable/axe.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/hoe.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/shovel.json
  src/generated/resources/data/minecraft/tags/blocks/needs_diamond_tool.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/generated/resources/data/minecraft/tags/blocks/needs_stone_tool.json
  src/main/java/com/gildedgames/aether/common/item/tools/abilities/IGravititeToolItem.java
  src/main/java/com/gildedgames/aether/core/data/AetherBlockTagData.java
Labels: priority/high, feat/item, feat/block

#382 Enhancement: Zephyr polishing
  src/main/java/com/gildedgames/aether/client/particle/WhiteSmokeParticle.java
  src/main/java/com/gildedgames/aether/client/registry/AetherParticleTypes.java
  src/main/java/com/gildedgames/aether/client/registry/AetherRenderers.java
  src/main/java/com/gildedgames/aether/common/entity/monster/ZephyrEntity.java
  src/main/java/com/gildedgames/aether/common/entity/projectile/ZephyrSnowballEntity.java
  src/main/java/com/gildedgames/aether/core/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/core/network/packet/client/ZephyrSnowballHitPacket.java
  src/main/resources/assets/aether/particles/zephyr_snowflake.json
Labels: status/pending-review, type/enhancement, feat/entity

#378 Fix: Mimic polishing
  src/generated/resources/.cache/cache
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/assets/aether/sounds.json
  src/main/java/com/gildedgames/aether/client/registry/AetherRenderers.java
  src/main/java/com/gildedgames/aether/client/registry/AetherSoundEvents.java
  src/main/java/com/gildedgames/aether/client/renderer/tile/ChestMimicBlockEntityRenderer.java
  src/main/java/com/gildedgames/aether/client/renderer/tile/ChestMimicRenderer.java
  src/main/java/com/gildedgames/aether/common/block/dungeon/ChestMimicBlock.java
  src/main/java/com/gildedgames/aether/common/entity/monster/dungeon/MimicEntity.java
  src/main/java/com/gildedgames/aether/core/data/AetherLangData.java
  src/main/java/com/gildedgames/aether/core/data/AetherSoundData.java
Labels: status/pending-review, type/enhancement, feat/entity, type/refactor

#188 Entity Polish Pull request
  src/main/java/com/gildedgames/aether/common/effect/InebriationEffect.java
  src/main/java/com/gildedgames/aether/common/entity/monster/AechorPlantEntity.java
  src/main/java/com/gildedgames/aether/common/entity/monster/dungeon/SentryEntity.java
Labels: version/1.18

#387 feat: Ported the content from feature/rankings_system.
  src/generated/resources/.cache/cache
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AccessoriesScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/perks/CustomizationScreen.java
  src/main/java/com/gildedgames/aether/client/registry/AetherModelLayers.java
  src/main/java/com/gildedgames/aether/client/registry/AetherRenderers.java
  src/main/java/com/gildedgames/aether/client/renderer/perks/layer/DeveloperGlowLayer.java
  src/main/java/com/gildedgames/aether/client/renderer/perks/layer/PlayerHaloLayer.java
  src/main/java/com/gildedgames/aether/client/renderer/perks/model/PlayerHaloModel.java
  src/main/java/com/gildedgames/aether/common/entity/monster/PassiveWhirlwind.java
  src/main/java/com/gildedgames/aether/common/event/AetherRankingRegistryEvent.java
  src/main/java/com/gildedgames/aether/common/event/events/RankingEvent.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherRankingsListener.java
  src/main/java/com/gildedgames/aether/core/api/AetherRank.java
  src/main/java/com/gildedgames/aether/core/api/AetherRankings.java
  src/main/java/com/gildedgames/aether/core/api/registers/PlayerRanking.java
  src/main/java/com/gildedgames/aether/core/capability/AetherCapabilities.java
  src/main/java/com/gildedgames/aether/core/capability/capabilities/rankings/AetherRankings.java
  src/main/java/com/gildedgames/aether/core/capability/capabilities/rankings/AetherRankingsProvider.java
  src/main/java/com/gildedgames/aether/core/capability/interfaces/IAetherRankings.java
  src/main/java/com/gildedgames/aether/core/data/AetherLangData.java
  src/main/java/com/gildedgames/aether/core/data/provider/AetherLanguageProvider.java
  src/main/java/com/gildedgames/aether/core/registry/AetherPlayerRankings.java
  src/main/resources/assets/aether/textures/models/halo/halo.png
  src/main/resources/assets/aether/textures/models/perks/halo.png
Labels: status/pending-review

#367 [1.18]add swet shrink animation
  src/main/java/com/gildedgames/aether/client/renderer/entity/SwetRenderer.java
  src/main/java/com/gildedgames/aether/common/entity/monster/SwetEntity.java
Labels: version/1.18

#391 fix: Fixed issue with the Rankings Capability preventing respawning.
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherPlayerListener.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherRankingsListener.java
Labels: status/pending-review

#393 refactor: Changed formatting of tag datagen code.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/tags/items/book_of_lore_materials.json
  src/main/java/com/gildedgames/aether/core/data/AetherBlockTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherEntityTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherFluidTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherItemTagData.java
Labels: status/pending-review

#392 refactor: Changed a check in DimensionTypeMixin.
  src/main/java/com/gildedgames/aether/core/mixin/common/DimensionTypeMixin.java
Labels: status/pending-review

#400 feat: Added and updated tags. Also updated Forge to latest due to some tag changes.
  gradle.properties
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/tags/items/dart_shooters.json
  src/generated/resources/data/aether/tags/items/darts.json
  src/generated/resources/data/forge/tags/blocks/ore_rates/singular.json
  src/generated/resources/data/forge/tags/blocks/sand/colorless.json
  src/generated/resources/data/forge/tags/items/eggs.json
  src/generated/resources/data/forge/tags/items/ore_rates/singular.json
  src/generated/resources/data/forge/tags/items/sand/colorless.json
  src/generated/resources/data/minecraft/tags/blocks/dirt.json
  src/generated/resources/data/minecraft/tags/blocks/sand.json
  src/generated/resources/data/minecraft/tags/entity_types/freeze_hurts_extra_types.json
  src/generated/resources/data/minecraft/tags/entity_types/powder_snow_walkable_mobs.json
  src/generated/resources/data/minecraft/tags/items/sand.json
  src/main/java/com/gildedgames/aether/common/registry/AetherTags.java
  src/main/java/com/gildedgames/aether/core/data/AetherBlockTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherEntityTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherItemTagData.java
Labels: status/pending-review

#427 fix: Added missing Fire Minion renderer.
  src/main/java/com/gildedgames/aether/client/registry/AetherRenderers.java
Labels: status/pending-review
