Repository The-Aether-Team/The-Aether, pull requests merged in 2022-08, with the labels that each got.

#737 refactor: Block Entity Refactors
  src/main/java/com/gildedgames/aether/blockentity/AbstractAetherFurnaceBlockEntity.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AbstractAetherFurnaceScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AltarScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/FreezerScreen.java
  src/main/java/com/gildedgames/aether/inventory/menu/AbstractAetherFurnaceMenu.java
  src/main/java/com/gildedgames/aether/inventory/menu/AltarMenu.java
  src/main/java/com/gildedgames/aether/inventory/menu/FreezerMenu.java
  src/main/java/com/gildedgames/aether/inventory/menu/slot/AetherFurnaceFuelSlot.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: status/pending-review

#744 fix: Icestone performance improvements.
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/api/ReloadListeners.java
  src/main/java/com/gildedgames/aether/block/FreezingBlock.java
  src/main/java/com/gildedgames/aether/block/construction/IcestoneSlabBlock.java
  src/main/java/com/gildedgames/aether/block/construction/IcestoneStairsBlock.java
  src/main/java/com/gildedgames/aether/block/construction/IcestoneWallBlock.java
  src/main/java/com/gildedgames/aether/block/natural/IcestoneBlock.java
  src/main/java/com/gildedgames/aether/blockentity/AetherBlockEntityTypes.java
  src/main/java/com/gildedgames/aether/blockentity/IcestoneBlockEntity.java
  src/main/java/com/gildedgames/aether/event/AetherGameEvents.java
  src/main/java/com/gildedgames/aether/event/hooks/DimensionHooks.java
  src/main/java/com/gildedgames/aether/event/listeners/DimensionListener.java
  src/main/java/com/gildedgames/aether/recipe/BlockPropertyPair.java
  src/main/java/com/gildedgames/aether/recipe/BlockStateIngredient.java
Labels: status/pending-review

#745 feat: 1.19.2 Port
  build.gradle
  gradle.properties
  src/generated/resources/.cache/248190968468b9dc2bff1b7b2131784d0d7857d4
  src/generated/resources/.cache/31e8da375e62dc325cd3de8be1b7d6a126a61eec
  src/generated/resources/.cache/3b0fe09deeb115c0ed24c9963614d6853a6f89e0
  src/generated/resources/.cache/4a620f08c2dd26e75e94524bbb71add0ad1bc325
  src/generated/resources/.cache/55f0273cb61243ff3d2fde23212f03e66541da02
  src/generated/resources/.cache/63a021942da19534fa76a96f23a5878ca1d9a371
  src/generated/resources/.cache/6a3d99b2dfe3b52b9e5c114da2da10317036c053
  src/generated/resources/.cache/735031f3addf80804addae5e3f53249900116f1e
  src/generated/resources/.cache/7448c942dea71deed59a9581856c68cf60b193de
  src/generated/resources/.cache/7452c67c310ec945bc69debcbc8a0b3dc4f92884
  src/generated/resources/.cache/797771fa92c9781c2c346f8c74e71a22b0dcdf25
  src/generated/resources/.cache/84fe6562c3263bad7911908ec1f7b4c6a74e7999
  src/generated/resources/.cache/878d7dc758db8dc2bb3a6288d38cb36a95bf701b
  src/generated/resources/.cache/8a4be48a5ee7e414aa9b943597b34daf4f2f95c1
  src/generated/resources/.cache/8d737e70c6a24665a953b569e247c243dce7a914
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/.cache/a676442aee94531405dc397b215bd68da3efd342
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/.cache/e4d7f7b05c507d533af44beac9beab0a9fabc42f
  src/generated/resources/.cache/f9f349c9a38c23d71c2b92e2db2e508baf1c26de
  src/generated/resources/.cache/ff81da177a6c8ae35f28123afe13c95ba48aa6bf
  src/generated/resources/data/aether/tags/items/accessories.json
  src/generated/resources/data/aether/tags/items/tools/hammers.json
  src/generated/resources/data/aether/tags/items/tools/lances.json
  src/generated/resources/data/forge/tags/items/armors/boots.json
  src/generated/resources/data/forge/tags/items/armors/chestplates.json
  src/generated/resources/data/forge/tags/items/armors/helmets.json
  src/generated/resources/data/forge/tags/items/armors/leggings.json
  src/generated/resources/data/forge/tags/items/tools.json
  src/generated/resources/data/forge/tags/items/tools/axes.json
  src/generated/resources/data/forge/tags/items/tools/bows.json
  src/generated/resources/data/forge/tags/items/tools/hoes.json
  src/generated/resources/data/forge/tags/items/tools/pickaxes.json
  src/generated/resources/data/forge/tags/items/tools/shovels.json
  src/generated/resources/data/forge/tags/items/tools/swords.json
  src/main/java/com/gildedgames/aether/AetherTags.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherItemTagData.java
  src/main/resources/META-INF/mods.toml
Labels: status/pending-review

#746 feat: Debugging Commands
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/command/AetherCommands.java
  src/main/java/com/gildedgames/aether/command/AetherMenuFixCommand.java
  src/main/java/com/gildedgames/aether/command/AetherTimeCommand.java
  src/main/java/com/gildedgames/aether/command/EternalDayCommand.java
  src/main/java/com/gildedgames/aether/command/PlayerCapabilityCommand.java
  src/main/java/com/gildedgames/aether/command/SunAltarWhitelistCommand.java
  src/main/java/com/gildedgames/aether/command/WorldPreviewFixCommand.java
  src/main/java/com/gildedgames/aether/data/generators/AetherLanguageData.java
  src/main/java/com/gildedgames/aether/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/network/packet/client/HealthResetPacket.java
Labels: type/feature, feat/system

#749 feat: JarInJar implementation of Curios as a dependency.
  CREDITS.txt
  build.gradle
  gradle.properties
  src/main/resources/META-INF/mods.toml
Labels: type/repo

#739 fix: Music fixes.
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/AetherConfig.java
  src/main/java/com/gildedgames/aether/api/WorldDisplayHelper.java
  src/main/java/com/gildedgames/aether/client/AetherMusicManager.java
  src/main/java/com/gildedgames/aether/client/event/hooks/AudioHooks.java
  src/main/java/com/gildedgames/aether/client/event/hooks/GuiHooks.java
  src/main/java/com/gildedgames/aether/client/event/hooks/LevelClientHooks.java
  src/main/java/com/gildedgames/aether/client/event/listeners/AudioListener.java
  src/main/java/com/gildedgames/aether/client/event/listeners/GuiListener.java
  src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherTitleScreen.java
  src/main/java/com/gildedgames/aether/command/WorldPreviewFixCommand.java
  src/main/java/com/gildedgames/aether/data/generators/AetherLanguageData.java
  src/main/java/com/gildedgames/aether/mixin/mixins/client/ConnectScreenMixin.java
  src/main/java/com/gildedgames/aether/mixin/mixins/client/CreateWorldScreenMixin.java
  src/main/java/com/gildedgames/aether/mixin/mixins/client/PanoramaRendererMixin.java
  src/main/java/com/gildedgames/aether/mixin/mixins/client/TitleScreenMixin.java
  src/main/java/com/gildedgames/aether/mixin/mixins/client/WorldListEntryMixin.java
Labels: type/enhancement, feat/system, feat/audio, type/refactor

#766 Silver Dungeon NBT files
  src/main/resources/data/aether/structures/silver_dungeon/boss_exterior.nbt
  src/main/resources/data/aether/structures/silver_dungeon/boss_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/chest_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/empty_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/entrance_exterior.nbt
  src/main/resources/data/aether/structures/silver_dungeon/staircase.nbt
  src/main/resources/data/aether/structures/silver_dungeon/tall_staircase.nbt
Labels: status/pending-review

#777 Update zh_cn translate.
  src/main/resources/assets/aether/lang/zh_cn.json
Labels: status/pending-review

#778 refactor: Update fr_fr translation
  src/main/resources/assets/aether/lang/fr_fr.json
Labels: status/pending-review, feat/copy

#768 feat: Slider
  src/generated/resources/.cache/6a3d99b2dfe3b52b9e5c114da2da10317036c053
  src/generated/resources/.cache/735031f3addf80804addae5e3f53249900116f1e
  src/generated/resources/.cache/797771fa92c9781c2c346f8c74e71a22b0dcdf25
  src/generated/resources/.cache/878d7dc758db8dc2bb3a6288d38cb36a95bf701b
  src/generated/resources/.cache/8d737e70c6a24665a953b569e247c243dce7a914
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/assets/aether/models/item/slider_spawn_egg.json
  src/generated/resources/assets/aether/sounds.json
  src/generated/resources/data/aether/advancements/bronze_dungeon.json
  src/generated/resources/data/aether/advancements/gold_dungeon.json
  src/generated/resources/data/aether/advancements/silver_dungeon.json
  src/generated/resources/data/aether/loot_tables/entities/slider.json
  src/generated/resources/data/aether/tags/items/slider_damaging_items.json
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/AetherTags.java
  src/main/java/com/gildedgames/aether/api/AetherDungeonTypes.java
  src/main/java/com/gildedgames/aether/api/BossNameGenerator.java
  src/main/java/com/gildedgames/aether/api/DungeonTracker.java
  src/main/java/com/gildedgames/aether/api/registers/DungeonType.java
  src/main/java/com/gildedgames/aether/block/dungeon/TreasureChestBlock.java
  src/main/java/com/gildedgames/aether/block/utility/IncubatorBlock.java
  src/main/java/com/gildedgames/aether/block/utility/SunAltarBlock.java
  src/main/java/com/gildedgames/aether/blockentity/SunAltarBlockEntity.java
  src/main/java/com/gildedgames/aether/blockentity/TreasureChestBlockEntity.java
  src/main/java/com/gildedgames/aether/client/AetherSoundEvents.java
  src/main/java/com/gildedgames/aether/client/gui/screen/ValkyrieQueenDialogueScreen.java
  src/main/java/com/gildedgames/aether/client/renderer/AetherModelLayers.java
  src/main/java/com/gildedgames/aether/client/renderer/AetherRenderers.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/AerbunnyRenderer.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/SliderRenderer.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/ValkyrieQueenRenderer.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/layers/SentryLayer.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/layers/SliderGlowLayer.java
  src/main/java/com/gildedgames/aether/client/renderer/entity/model/SliderModel.java
  src/main/java/com/gildedgames/aether/data/generators/AetherAdvancementData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherEntityLootData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherItemModelData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherLanguageData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherSoundData.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherItemTagData.java
  src/main/java/com/gildedgames/aether/entity/AetherEntityTypes.java
  src/main/java/com/gildedgames/aether/entity/BossRoom.java
  src/main/java/com/gildedgames/aether/entity/ai/controller/SliderMovementController.java
  src/main/java/com/gildedgames/aether/entity/ai/goal/target/InBossRoomTargetGoal.java
  src/main/java/com/gildedgames/aether/entity/ai/goal/target/MostDamageTargetGoal.java
  src/main/java/com/gildedgames/aether/entity/monster/PassiveWhirlwind.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/Valkyrie.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/Slider.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/ValkyrieQueen.java
  src/main/java/com/gildedgames/aether/event/hooks/EntityHooks.java
  src/main/java/com/gildedgames/aether/event/listeners/EntityListener.java
  src/main/java/com/gildedgames/aether/item/AetherItems.java
  src/main/java/com/gildedgames/aether/item/miscellaneous/DungeonKeyItem.java
  src/main/java/com/gildedgames/aether/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/network/packet/client/OpenSunAltarPacket.java
Labels: status/pending-review, type/feature, feat/entity

#781 refactor: Additions to the Accessory Menu
  src/main/java/com/gildedgames/aether/client/event/hooks/GuiHooks.java
  src/main/java/com/gildedgames/aether/client/event/listeners/GuiListener.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AccessoriesScreen.java
  src/main/java/com/gildedgames/aether/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/network/packet/server/ClearItemPacket.java
  src/main/resources/assets/aether/textures/gui/inventory/accessories_creative.png
Labels: status/pending-review, type/design, feat/gui

#783 feat: Configurable Silver Life Shard Hearts
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/AetherConfig.java
  src/main/java/com/gildedgames/aether/client/renderer/AetherOverlays.java
  src/main/java/com/gildedgames/aether/data/generators/AetherLanguageData.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/aether/textures/gui/life_shard_hearts.png
Labels: type/design, feat/config, feat/gui

#784 Locked Silver Dungeon
  src/main/resources/data/aether/structures/silver_dungeon/boss_exterior.nbt
  src/main/resources/data/aether/structures/silver_dungeon/boss_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/chest_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/empty_room.nbt
  src/main/resources/data/aether/structures/silver_dungeon/entrance_exterior.nbt
  src/main/resources/data/aether/structures/silver_dungeon/staircase.nbt
  src/main/resources/data/aether/structures/silver_dungeon/tall_staircase.nbt
Labels: status/pending-review, type/design, feat/world-gen

#789 Sun spirit fixes
  src/main/java/com/gildedgames/aether/entity/AetherEntityTypes.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/FireMinion.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/SunSpirit.java
  src/main/java/com/gildedgames/aether/entity/projectile/crystal/IceCrystal.java
Labels: status/pending-review

#788 Quicksoil no longer replaces Holystone and Aether Dirt
  src/main/java/com/gildedgames/aether/util/BlockPlacementUtil.java
Labels: status/pending-review

#786 Feat: Invisible Blocks
  src/generated/resources/.cache/6a3d99b2dfe3b52b9e5c114da2da10317036c053
  src/generated/resources/.cache/878d7dc758db8dc2bb3a6288d38cb36a95bf701b
  src/generated/resources/.cache/a676442aee94531405dc397b215bd68da3efd342
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/blockstates/boss_doorway_angelic_stone.json
  src/generated/resources/assets/aether/blockstates/boss_doorway_carved_stone.json
  src/generated/resources/assets/aether/blockstates/boss_doorway_hellfire_stone.json
  src/generated/resources/assets/aether/blockstates/treasure_doorway_angelic_stone.json
  src/generated/resources/assets/aether/blockstates/treasure_doorway_carved_stone.json
  src/generated/resources/assets/aether/blockstates/treasure_doorway_hellfire_stone.json
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/assets/aether/models/block/boss_doorway_angelic_stone.json
  src/generated/resources/assets/aether/models/block/boss_doorway_carved_stone.json
  src/generated/resources/assets/aether/models/block/boss_doorway_hellfire_stone.json
  src/generated/resources/assets/aether/models/block/treasure_doorway_angelic_stone.json
  src/generated/resources/assets/aether/models/block/treasure_doorway_carved_stone.json
  src/generated/resources/assets/aether/models/block/treasure_doorway_hellfire_stone.json
  src/generated/resources/assets/aether/models/item/boss_doorway_angelic_stone.json
  src/generated/resources/assets/aether/models/item/boss_doorway_carved_stone.json
  src/generated/resources/assets/aether/models/item/boss_doorway_hellfire_stone.json
  src/generated/resources/assets/aether/models/item/treasure_doorway_angelic_stone.json
  src/generated/resources/assets/aether/models/item/treasure_doorway_carved_stone.json
  src/generated/resources/assets/aether/models/item/treasure_doorway_hellfire_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/boss_doorway_angelic_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/boss_doorway_carved_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/boss_doorway_hellfire_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/treasure_doorway_angelic_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/treasure_doorway_carved_stone.json
  src/generated/resources/data/aether/loot_tables/blocks/treasure_doorway_hellfire_stone.json
  src/main/java/com/gildedgames/aether/api/DungeonTracker.java
  src/main/java/com/gildedgames/aether/block/AetherBlocks.java
  src/main/java/com/gildedgames/aether/block/dungeon/InvisibleBlock.java
  src/main/java/com/gildedgames/aether/block/dungeon/TreasureRoomBlock.java
  src/main/java/com/gildedgames/aether/blockentity/TreasureChestBlockEntity.java
  src/main/java/com/gildedgames/aether/data/generators/AetherBlockStateData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherItemModelData.java
  src/main/java/com/gildedgames/aether/data/generators/AetherLanguageData.java
  src/main/java/com/gildedgames/aether/data/generators/loot/AetherBlockLootData.java
  src/main/java/com/gildedgames/aether/data/providers/AetherBlockStateProvider.java
  src/main/java/com/gildedgames/aether/data/providers/AetherItemModelProvider.java
  src/main/java/com/gildedgames/aether/entity/BossMob.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/Slider.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/SunSpirit.java
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/boss/ValkyrieQueen.java
  src/main/java/com/gildedgames/aether/world/processor/HellfireStoneProcessor.java
  src/main/java/com/gildedgames/aether/world/structurepiece/GoldDungeonPieces.java
  src/main/resources/data/aether/structures/gold_dungeon/boss_room.nbt
Labels: status/pending-review
