Repository The-Aether-Team/The-Aether, pull requests merged in 2022-04, with the labels that each got.

#532 fix: Fix server crash from entering the Aether.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/tags/dimension_type/aether_music.json
  src/generated/resources/data/aether/tags/dimension_type/eternal_day.json
  src/generated/resources/data/aether/tags/dimension_type/fall_to_overworld.json
  src/generated/resources/data/aether/tags/dimension_type/hostile_paradise.json
  src/generated/resources/data/aether/tags/dimension_type/no_wheat_seeds.json
  src/generated/resources/data/aether/tags/dimension_type/ultracold.json
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/client/event/listeners/GuiListener.java
  src/main/java/com/gildedgames/aether/client/world/AetherSkyRenderer.java
  src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherTimeListener.java
  src/main/java/com/gildedgames/aether/common/loot/modifiers/RemoveSeedsModifier.java
  src/main/java/com/gildedgames/aether/common/registry/AetherDispenseBehaviors.java
  src/main/java/com/gildedgames/aether/common/registry/AetherTags.java
  src/main/java/com/gildedgames/aether/core/capability/AetherCapabilities.java
  src/main/java/com/gildedgames/aether/core/data/AetherDimensionTagData.java
  src/main/java/com/gildedgames/aether/core/data/provider/DimensionTagsProvider.java
  src/main/java/com/gildedgames/aether/core/mixin/client/MinecraftMixin.java
Labels: status/in-progress

#527 Feat: recipe books for Aether utility blocks
  src/generated/resources/.cache/cache
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/client/AetherClient.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AccessoriesScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AetherFurnaceScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/AltarScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/FreezerScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/IncubatorScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/LoreBookScreen.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/recipebook/AltarRecipeBookComponent.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/recipebook/FreezerRecipeBookComponent.java
  src/main/java/com/gildedgames/aether/client/gui/screen/inventory/recipebook/package-info.java
  src/main/java/com/gildedgames/aether/client/registry/AetherRecipeCategories.java
  src/main/java/com/gildedgames/aether/common/block/entity/AltarBlockEntity.java
  src/main/java/com/gildedgames/aether/common/block/entity/FreezerBlockEntity.java
  src/main/java/com/gildedgames/aether/common/block/entity/IncubatorBlockEntity.java
  src/main/java/com/gildedgames/aether/common/block/utility/SunAltarBlock.java
  src/main/java/com/gildedgames/aether/common/inventory/LoreInventory.java
  src/main/java/com/gildedgames/aether/common/inventory/container/AccessoriesMenu.java
  src/main/java/com/gildedgames/aether/common/inventory/container/AltarMenu.java
  src/main/java/com/gildedgames/aether/common/inventory/container/FreezerMenu.java
  src/main/java/com/gildedgames/aether/common/inventory/container/IncubatorMenu.java
  src/main/java/com/gildedgames/aether/common/inventory/container/LoreBookMenu.java
  src/main/java/com/gildedgames/aether/common/inventory/container/slot/IncubatorEggSlot.java
  src/main/java/com/gildedgames/aether/common/inventory/container/slot/IncubatorFuelSlot.java
  src/main/java/com/gildedgames/aether/common/inventory/provider/AccessoriesProvider.java
  src/main/java/com/gildedgames/aether/common/inventory/provider/LoreBookProvider.java
  src/main/java/com/gildedgames/aether/common/registry/AetherContainerTypes.java
  src/main/java/com/gildedgames/aether/common/registry/AetherRecipeBookTypes.java
  src/main/java/com/gildedgames/aether/core/data/AetherLangData.java
  src/main/java/com/gildedgames/aether/core/mixin/client/ClientRecipeBookMixin.java
  src/main/java/com/gildedgames/aether/core/network/packet/server/LoreExistsPacket.java
  src/main/resources/aether.mixins.json
Labels: status/in-progress, feat/item, feat/block, type/refactor, feat/gui

#494 Fix: Aerclouds are now valid spawn blocks.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/tags/entity_types/aercloud_spawnable.json
  src/main/java/com/gildedgames/aether/common/block/natural/AercloudBlock.java
  src/main/java/com/gildedgames/aether/common/entity/monster/Cockatrice.java
  src/main/java/com/gildedgames/aether/common/entity/monster/Zephyr.java
  src/main/java/com/gildedgames/aether/common/entity/passive/Aerwhale.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
  src/main/java/com/gildedgames/aether/common/registry/AetherTags.java
  src/main/java/com/gildedgames/aether/core/data/AetherEntityTagData.java
Labels: status/pending-review

#543 refactor: Zanite weapon math improvement.
  src/main/java/com/gildedgames/aether/common/item/combat/abilities/weapon/ZaniteWeapon.java
Labels: status/pending-review

#546 fix: Use getMaxBuildHeight instead of getHeight for where to place the player when falling out of the Aether.
  src/main/java/com/gildedgames/aether/common/world/AetherTeleporter.java
Labels: status/pending-review

#547 fix: Fixed opacity issues with overlays.
  src/main/java/com/gildedgames/aether/client/registry/AetherOverlays.java
Labels: status/pending-review

#544 fix: GUI Fixes
  src/generated/resources/.cache/cache
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/client/event/hooks/DimensionClientHooks.java
  src/main/java/com/gildedgames/aether/client/event/hooks/GuiHooks.java
  src/main/java/com/gildedgames/aether/client/event/listeners/DimensionClientListener.java
  src/main/java/com/gildedgames/aether/client/event/listeners/GuiListener.java
  src/main/java/com/gildedgames/aether/common/event/hooks/DimensionHooks.java
  src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java
  src/main/java/com/gildedgames/aether/common/inventory/container/LoreBookMenu.java
  src/main/java/com/gildedgames/aether/core/data/AetherLangData.java
  src/main/java/com/gildedgames/aether/core/data/AetherLanguageData.java
  src/main/java/com/gildedgames/aether/core/data/provider/AetherLanguageProvider.java
  src/main/java/com/gildedgames/aether/core/util/TriviaReader.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/aether/texts/trivia/en_us.txt
Labels: status/pending-review

#551 fix: Gravitite Ore floating improvements.
  src/main/java/com/gildedgames/aether/common/block/util/FloatingBlock.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
Labels: status/pending-review

#550 fix: Aercloud fall damage fix.
  src/main/java/com/gildedgames/aether/common/block/natural/AercloudBlock.java
  src/main/java/com/gildedgames/aether/common/block/natural/BlueAercloudBlock.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
Labels: status/pending-review

#552 fix: Various recipe fixes; ores and recipes now give XP.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/advancements/recipes/aether_accessories/ice_pendant_from_freezing.json
  src/generated/resources/data/aether/advancements/recipes/aether_accessories/ice_ring_from_freezing.json
  src/generated/resources/data/aether/advancements/recipes/aether_accessories/ice_ring_from_gold_freezing.json
  src/generated/resources/data/aether/advancements/recipes/building_blocks/blue_ice_freezing.json
  src/generated/resources/data/aether/advancements/recipes/building_blocks/ice_from_bucket_freezing.json
  src/generated/resources/data/aether/advancements/recipes/building_blocks/obsidian_from_bucket_freezing.json
  src/generated/resources/data/aether/advancements/recipes/building_blocks/packed_ice_freezing.json
  src/generated/resources/data/aether/recipes/aether_tune_enchanting.json
  src/generated/resources/data/aether/recipes/blue_aercloud_freezing.json
  src/generated/resources/data/aether/recipes/blue_ice_freezing.json
  src/generated/resources/data/aether/recipes/crystal_leaves_freezing.json
  src/generated/resources/data/aether/recipes/enchanted_berry_enchanting.json
  src/generated/resources/data/aether/recipes/enchanted_dart_enchanting.json
  src/generated/resources/data/aether/recipes/enchanted_dart_shooter_enchanting.json
  src/generated/resources/data/aether/recipes/enchanted_gravitite_enchanting.json
  src/generated/resources/data/aether/recipes/healing_stone_enchanting.json
  src/generated/resources/data/aether/recipes/ice_from_bucket_freezing.json
  src/generated/resources/data/aether/recipes/ice_pendant_from_freezing.json
  src/generated/resources/data/aether/recipes/ice_pendant_from_gold_freezing.json
  src/generated/resources/data/aether/recipes/ice_ring_from_freezing.json
  src/generated/resources/data/aether/recipes/ice_ring_from_iron_freezing.json
  src/generated/resources/data/aether/recipes/legacy_enchanting.json
  src/generated/resources/data/aether/recipes/obsidian_from_bucket_freezing.json
  src/generated/resources/data/aether/recipes/packed_ice_freezing.json
  src/generated/resources/data/aether/recipes/quicksoil_glass_enchanting.json
  src/generated/resources/data/aether/recipes/remedy_bucket_enchanting.json
  src/generated/resources/data/aether/recipes/welcoming_skies_freezing.json
  src/generated/resources/data/aether/tags/items/freezable_buckets.json
  src/generated/resources/data/aether/tags/items/freezable_pendants.json
  src/generated/resources/data/aether/tags/items/freezable_rings.json
  src/main/java/com/gildedgames/aether/common/block/natural/AetherOreBlock.java
  src/main/java/com/gildedgames/aether/common/block/util/AetherDoubleDropsOreBlock.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
  src/main/java/com/gildedgames/aether/common/registry/AetherTags.java
  src/main/java/com/gildedgames/aether/core/data/AetherItemTagData.java
  src/main/java/com/gildedgames/aether/core/data/AetherRecipeData.java
  src/main/java/com/gildedgames/aether/core/data/provider/AetherRecipeProvider.java
  src/main/java/com/gildedgames/aether/core/mixin/common/AbstractFurnaceBlockEntityMixin.java
Labels: status/pending-review

#558 refactor: Moved Aether spawn eggs to Aether Miscellaneous tab.
  src/main/java/com/gildedgames/aether/common/registry/AetherItems.java
Labels: status/pending-review

#557 feat: Mixin plugin and config.
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/core/mixin/AetherMixinConfig.java
  src/main/java/com/gildedgames/aether/core/mixin/AetherMixinPlugin.java
  src/main/java/com/gildedgames/aether/core/mixin/common/AbstractArrowMixin.java
  src/main/java/com/gildedgames/aether/core/util/SunAltarWhitelist.java
  src/main/resources/aether.mixins.json
Labels: status/pending-review

#548 feat: Dimension Type tags and config for portal send and return destinations.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/tags/dimension_type/aether_music.json
  src/generated/resources/data/aether/tags/dimension_type/display_travel_text.json
  src/generated/resources/data/aether/tags/dimension_type/eternal_day.json
  src/generated/resources/data/aether/tags/dimension_type/fall_to_overworld.json
  src/generated/resources/data/aether/tags/dimension_type/hostile_paradise.json
  src/generated/resources/data/aether/tags/dimension_type/no_wheat_seeds.json
  src/generated/resources/data/aether/tags/dimension_type/ultracold.json
  src/main/java/com/gildedgames/aether/Aether.java
  src/main/java/com/gildedgames/aether/client/event/hooks/DimensionClientHooks.java
  src/main/java/com/gildedgames/aether/client/event/hooks/GuiHooks.java
  src/main/java/com/gildedgames/aether/client/event/listeners/DimensionClientListener.java
  src/main/java/com/gildedgames/aether/common/block/miscellaneous/AetherPortalBlock.java
  src/main/java/com/gildedgames/aether/common/entity/monster/Swet.java
  src/main/java/com/gildedgames/aether/common/event/hooks/CapabilityHooks.java
  src/main/java/com/gildedgames/aether/common/event/hooks/DimensionHooks.java
  src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherTimeListener.java
  src/main/java/com/gildedgames/aether/common/loot/modifiers/RemoveSeedsModifier.java
  src/main/java/com/gildedgames/aether/common/registry/AetherDispenseBehaviors.java
  src/main/java/com/gildedgames/aether/common/registry/AetherTags.java
  src/main/java/com/gildedgames/aether/common/world/AetherTeleporter.java
  src/main/java/com/gildedgames/aether/core/AetherConfig.java
  src/main/java/com/gildedgames/aether/core/capability/AetherCapabilities.java
  src/main/java/com/gildedgames/aether/core/data/AetherDimensionTagData.java
  src/main/java/com/gildedgames/aether/core/data/provider/DimensionTagsProvider.java
  src/main/java/com/gildedgames/aether/core/mixin/client/MinecraftMixin.java
  src/main/java/com/gildedgames/aether/core/mixin/common/DimensionTypeMixin.java
  src/main/java/com/gildedgames/aether/core/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/core/network/packet/client/AetherTravelPacket.java
  src/main/java/com/gildedgames/aether/core/network/packet/client/DimensionTypeHolderPacket.java
  src/main/java/com/gildedgames/aether/core/network/packet/client/LeavingAetherPacket.java
  src/main/java/com/gildedgames/aether/core/util/LevelUtil.java
Labels: status/pending-review

#562 refactor: Capability syncing system.
  src/main/java/com/gildedgames/aether/common/event/hooks/AbilityHooks.java
  src/main/java/com/gildedgames/aether/common/item/combat/abilities/armor/ValkyrieArmor.java
  src/main/java/com/gildedgames/aether/common/item/miscellaneous/LifeShardItem.java
  src/main/java/com/gildedgames/aether/core/capability/CapabilitySyncing.java
  src/main/java/com/gildedgames/aether/core/capability/INBTSynchable.java
  src/main/java/com/gildedgames/aether/core/capability/player/AetherPlayer.java
  src/main/java/com/gildedgames/aether/core/capability/player/AetherPlayerCapability.java
  src/main/java/com/gildedgames/aether/core/capability/rankings/AetherRankings.java
  src/main/java/com/gildedgames/aether/core/capability/rankings/AetherRankingsCapability.java
  src/main/java/com/gildedgames/aether/core/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/core/network/packet/AetherPlayerSyncPacket.java
  src/main/java/com/gildedgames/aether/core/network/packet/AetherRankingsSyncPacket.java
Labels: status/pending-review

#563 Feat: Added most of the remaining features for generation
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/worldgen/biome/golden_forest.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_forest.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_grove.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_thicket.json
  src/generated/resources/data/aether/worldgen/configured_feature/grass_patch.json
  src/generated/resources/data/aether/worldgen/configured_feature/tall_grass_patch.json
  src/generated/resources/data/aether/worldgen/configured_feature/water_lake.json
  src/generated/resources/data/aether/worldgen/configured_feature/water_spring.json
  src/generated/resources/data/aether/worldgen/placed_feature/grass_patch.json
  src/generated/resources/data/aether/worldgen/placed_feature/pink_aercloud.json
  src/generated/resources/data/aether/worldgen/placed_feature/tall_grass_patch.json
  src/generated/resources/data/aether/worldgen/placed_feature/water_lake.json
  src/generated/resources/data/aether/worldgen/placed_feature/water_spring.json
  src/main/java/com/gildedgames/aether/common/loot/conditions/ConfigEnabled.java
  src/main/java/com/gildedgames/aether/common/registry/worldgen/AetherFeatures.java
  src/main/java/com/gildedgames/aether/common/world/builders/AetherBiomeBuilders.java
  src/main/java/com/gildedgames/aether/common/world/builders/AetherFeatureBuilders.java
  src/main/java/com/gildedgames/aether/common/world/gen/placement/ConfigFilter.java
  src/main/java/com/gildedgames/aether/common/world/gen/placement/PlacementModifiers.java
Labels: status/pending-review

#564 refactor: ConfigSerializer.
  src/generated/resources/.cache/cache
  src/generated/resources/data/aether/worldgen/biome/golden_forest.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_forest.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_grove.json
  src/generated/resources/data/aether/worldgen/biome/skyroot_thicket.json
  src/generated/resources/data/aether/worldgen/placed_feature/grass_patch.json
  src/generated/resources/data/aether/worldgen/placed_feature/pink_aercloud.json
  src/generated/resources/data/aether/worldgen/placed_feature/tall_grass_patch.json
  src/main/java/com/gildedgames/aether/common/loot/conditions/ConfigEnabled.java
  src/main/java/com/gildedgames/aether/common/registry/worldgen/AetherFeatures.java
  src/main/java/com/gildedgames/aether/common/world/gen/placement/ConfigFilter.java
  src/main/java/com/gildedgames/aether/core/util/ConfigSerializer.java
Labels: status/pending-review

#572 Fix: Hopefully fixed the capability desync issues.
  src/main/java/com/gildedgames/aether/common/event/hooks/AbilityHooks.java
  src/main/java/com/gildedgames/aether/common/item/accessories/abilities/RepulsionShieldAccessory.java
  src/main/java/com/gildedgames/aether/common/item/combat/abilities/armor/ValkyrieArmor.java
  src/main/java/com/gildedgames/aether/common/item/food/WhiteAppleItem.java
  src/main/java/com/gildedgames/aether/common/item/miscellaneous/bucket/SkyrootRemedyBucketItem.java
  src/main/java/com/gildedgames/aether/core/capability/CapabilitySyncing.java
  src/main/java/com/gildedgames/aether/core/capability/player/AetherPlayerCapability.java
  src/main/java/com/gildedgames/aether/core/capability/rankings/AetherRankingsCapability.java
Labels: status/pending-review

#574 fix: Time no longer breaks and follows the Overworld's cycle when first joining a server in the Aether.
  src/main/java/com/gildedgames/aether/client/event/hooks/CapabilityClientHooks.java
  src/main/java/com/gildedgames/aether/client/event/listeners/capability/AetherTimeClientListener.java
  src/main/java/com/gildedgames/aether/common/event/hooks/DimensionHooks.java
  src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java
  src/main/java/com/gildedgames/aether/core/capability/time/AetherTimeCapability.java
Labels: status/pending-review

#575 refactor: Proper capability syncing upon dimension travel.
  src/main/java/com/gildedgames/aether/common/event/hooks/CapabilityHooks.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherPlayerListener.java
  src/main/java/com/gildedgames/aether/common/event/listeners/capability/AetherRankingsListener.java
  src/main/java/com/gildedgames/aether/core/capability/CapabilitySyncing.java
Labels: status/pending-review

#573 fix: Fixes to fall speeds and Valkyrie Armor.
  src/main/java/com/gildedgames/aether/common/entity/miscellaneous/Parachute.java
  src/main/java/com/gildedgames/aether/common/entity/monster/Cockatrice.java
  src/main/java/com/gildedgames/aether/common/entity/passive/Aerbunny.java
  src/main/java/com/gildedgames/aether/common/entity/passive/Moa.java
  src/main/java/com/gildedgames/aether/common/entity/passive/Sheepuff.java
  src/main/java/com/gildedgames/aether/common/entity/passive/WingedAnimal.java
  src/main/java/com/gildedgames/aether/common/event/listeners/abilities/AccessoryAbilityListener.java
  src/main/java/com/gildedgames/aether/common/item/accessories/abilities/SlowFallAccessory.java
  src/main/java/com/gildedgames/aether/common/item/combat/abilities/armor/ValkyrieArmor.java
  src/main/java/com/gildedgames/aether/common/registry/AetherBlocks.java
  src/main/java/com/gildedgames/aether/core/network/AetherPacketHandler.java
  src/main/java/com/gildedgames/aether/core/network/packet/client/ExplosionParticlePacket.java
  src/main/java/com/gildedgames/aether/core/network/packet/server/AerbunnyPuffPacket.java
Labels: status/pending-review

#576 feat: Mixin to prevent podzol replacing aether grass.
  src/main/java/com/gildedgames/aether/core/mixin/common/FeatureMixin.java
  src/main/resources/aether.mixins.json
Labels: status/pending-review

#582 fix: Check for null tag in packets.
  src/main/java/com/gildedgames/aether/core/network/packet/AetherPlayerSyncPacket.java
  src/main/java/com/gildedgames/aether/core/network/packet/AetherRankingsSyncPacket.java
Labels: status/pending-review
