Repository The-Aether-Team/The-Aether, pull requests merged in 2023-04, with the labels that each got.

#1109 refactor!: Update Forge and resolve breaking changes
  gradle.properties
  src/main/java/com/gildedgames/aether/client/particle/AetherParticleTypes.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherItemTagData.java
  src/main/java/com/gildedgames/aether/event/hooks/AbilityHooks.java
  src/main/java/com/gildedgames/aether/item/miscellaneous/bucket/SkyrootBucketItem.java
  src/main/java/com/gildedgames/aether/item/tools/abilities/ValkyrieTool.java
  src/main/java/com/gildedgames/aether/mixin/mixins/common/ItemMixin.java
Labels: status/pending-review

#1115 feat: Bring back JEI compatibility
  build.gradle
  gradle.properties
  src/main/java/com/gildedgames/aether/integration/jei/AetherJEIPlugin.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/AbstractAetherCookingRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/AltarRepairRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/AmbrosiumRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/EnchantingCookingRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/FreezingRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/IncubationRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/SwetBallRecipeCategory.java
  src/main/java/com/gildedgames/aether/integration/jei/categories/fuel/AetherFuelCategory.java
Labels: status/pending-review

#1120 fix(block): Correct slab hardness
  src/main/java/com/gildedgames/aether/block/AetherBlocks.java
Labels: feat/block

#1119 improv(block): isFertile check for Aether Farmland
  src/main/java/com/gildedgames/aether/block/construction/AetherFarmBlock.java
Labels: feat/block

#1139 refactor: Stackable Moa Eggs
  src/main/java/com/gildedgames/aether/item/AetherItems.java
Labels: status/pending-review, feat/item

#1136 refactor: Change various textures to be beta-accurate
  src/main/resources/packs/classic_base/assets/aether/textures/block/construction/aether_dirt_path_side.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/construction/aether_farmland.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/construction/aether_farmland_moist.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/aether_dirt.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/aether_grass_block_side.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/aether_grass_block_snow.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/aether_grass_block_top.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/enchanted_aether_grass_block_side.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/golden_oak_sapling.png
  src/main/resources/packs/classic_base/assets/aether/textures/block/natural/skyroot_sapling.png
  src/main/resources/packs/classic_base/assets/aether/textures/item/miscellaneous/moa_egg.png
  src/main/resources/packs/classic_base/assets/aether/textures/item/miscellaneous/moa_egg_spot.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/gravitite_gloves_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/gravitite_gloves_slim_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/neptune_gloves_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/neptune_gloves_slim_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/obsidian_gloves_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/obsidian_gloves_slim_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/zanite_gloves_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/gloves/zanite_gloves_slim_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/accessory/pendant/zanite_pendant_accessory.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/gravitite_layer_1.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/gravitite_layer_2.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/neptune_layer_1.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/neptune_layer_2.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/obsidian_layer_1.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/obsidian_layer_2.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/zanite_layer_1.png
  src/main/resources/packs/classic_base/assets/aether/textures/models/armor/zanite_layer_2.png
Labels: status/pending-review, feat/art

#1135 fix: Enchanted Grass Blocks don't disappear with Skyroot Shovels
  src/generated/resources/.cache/232d7dc54f63e89526c247ba29265b5afad0215c
  src/generated/resources/.cache/59eb3dbb5f86130e09b3c62d89b9525ee01cf52d
  src/generated/resources/data/aether/loot_tables/blocks/enchanted_aether_grass_block.json
  src/generated/resources/data/aether/tags/items/slider_damaging_items.json
  src/generated/resources/data/minecraft/tags/items/axes.json
  src/generated/resources/data/minecraft/tags/items/hoes.json
  src/generated/resources/data/minecraft/tags/items/pickaxes.json
  src/generated/resources/data/minecraft/tags/items/shovels.json
  src/generated/resources/data/minecraft/tags/items/swords.json
  src/main/java/com/gildedgames/aether/data/generators/loot/AetherBlockLoot.java
Labels: status/pending-review

#1140 feat: Skyroot Chest Boat programmer art
  docs/CREDITS.txt
  src/main/resources/packs/classic_base/assets/aether/textures/entity/miscellaneous/chest_boat/skyroot.png
  src/main/resources/packs/classic_base/assets/aether/textures/item/miscellaneous/skyroot_chest_boat.png
Labels: status/pending-review, feat/art

#1141 refactor: Change grass heightmap to MOTION_BLOCKING
  src/generated/resources/.cache/103d9f3f36b01595f1aa5172191e60eff02e6924
  src/generated/resources/data/aether/worldgen/placed_feature/grass_patch.json
  src/main/java/com/gildedgames/aether/data/resources/registries/AetherPlacedFeatures.java
Labels: status/pending-review

#1142 fix: Proper cape rotation
  src/main/java/com/gildedgames/aether/client/renderer/accessory/CapeRenderer.java
Labels: status/pending-review

#1144 fix: Guardians will properly target invisible players
  src/generated/resources/.cache/0fe122e549a2e3aeeca535edbc3649f31121d28e
  src/generated/resources/data/aether/tags/entity_types/ignore_invisibility.json
  src/main/java/com/gildedgames/aether/AetherTags.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherEntityTagData.java
  src/main/java/com/gildedgames/aether/event/listeners/abilities/AccessoryAbilityListener.java
Labels: status/pending-review

#1145 feat: Swet tag, Swet Ball tag, public moveParachute method
  src/generated/resources/.cache/0fe122e549a2e3aeeca535edbc3649f31121d28e
  src/generated/resources/.cache/232d7dc54f63e89526c247ba29265b5afad0215c
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/data/aether/advancements/recipes/redstone/swet_slime_block.json
  src/generated/resources/data/aether/advancements/recipes/redstone/swet_sticky_piston.json
  src/generated/resources/data/aether/advancements/recipes/tools/swet_lead.json
  src/generated/resources/data/aether/recipes/swet_lead.json
  src/generated/resources/data/aether/recipes/swet_slime_block.json
  src/generated/resources/data/aether/recipes/swet_sticky_piston.json
  src/generated/resources/data/aether/tags/entity_types/swets.json
  src/generated/resources/data/aether/tags/items/swet_balls.json
  src/main/java/com/gildedgames/aether/AetherTags.java
  src/main/java/com/gildedgames/aether/data/generators/AetherRecipeData.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherEntityTagData.java
  src/main/java/com/gildedgames/aether/data/generators/tags/AetherItemTagData.java
  src/main/java/com/gildedgames/aether/entity/miscellaneous/Parachute.java
Labels: status/pending-review

#1162 fix: Aether Portal plays correct sounds
  src/main/java/com/gildedgames/aether/block/portal/AetherPortalBlock.java
  src/main/java/com/gildedgames/aether/block/portal/AetherPortalForcer.java
Labels: status/pending-review

#1161 fix: Holystone components use correct sounds
  src/main/java/com/gildedgames/aether/block/AetherBlocks.java
Labels: status/pending-review

#1160 fix: Fire Minions will now target other attackers
  src/main/java/com/gildedgames/aether/entity/monster/dungeon/FireMinion.java
Labels: status/pending-review

#1151 fix: Book of Lore won't cause food consumption
  src/main/java/com/gildedgames/aether/item/miscellaneous/LoreBookItem.java
Labels: status/pending-review

#1150 improv: Crystal Tree Trunk Placer
  src/generated/resources/.cache/103d9f3f36b01595f1aa5172191e60eff02e6924
  src/generated/resources/data/aether/worldgen/configured_feature/crystal_tree.json
  src/main/java/com/gildedgames/aether/data/resources/registries/AetherConfiguredFeatures.java
  src/main/java/com/gildedgames/aether/world/trunkplacer/AetherTrunkPlacerTypes.java
  src/main/java/com/gildedgames/aether/world/trunkplacer/CrystalTreeTrunkPlacer.java
Labels: status/pending-review

#1092 Enhancement: Slider behaviour experiments
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/slider/Slider.java
Labels: status/in-progress

#1164 update: Curios 5.1.4.2->5.1.5.0
  gradle.properties
Labels: status/pending-review

#1171 refactor: Neptune Armor no longer attribute-based
  src/main/java/com/aetherteam/aether/event/listeners/abilities/ArmorAbilityListener.java
  src/main/java/com/aetherteam/aether/item/AetherItems.java
  src/main/java/com/aetherteam/aether/item/accessories/gloves/NeptuneGlovesItem.java
  src/main/java/com/aetherteam/aether/item/combat/abilities/armor/NeptuneArmor.java
  src/main/java/com/aetherteam/aether/item/combat/loot/NeptuneArmorItem.java
Labels: status/pending-review

#1169 refactor: Nature Staff uses 1 durability
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
Labels: status/pending-review

#1175 fix: Aechor Plants target attackers and Fire Minions wander
  src/main/java/com/aetherteam/aether/entity/monster/AechorPlant.java
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/FireMinion.java
Labels: status/pending-review

#1174 fix: Aether crafters give xp
  src/main/java/com/aetherteam/aether/blockentity/AbstractAetherFurnaceBlockEntity.java
Labels: status/pending-review

#1177 refactor: Dungeon Loot balance changes
  src/generated/resources/.cache/59eb3dbb5f86130e09b3c62d89b9525ee01cf52d
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon_disc.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon_gummies.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon_reward.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon_trash.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/bronze_dungeon_treasure.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/silver_dungeon_gravitite.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/silver_dungeon_gummies.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/silver_dungeon_neptune.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/silver_dungeon_treasure.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/bronze/silver_dungeon_valkyrie.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/silver/silver_dungeon_disc.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/silver/silver_dungeon_loot.json
  src/generated/resources/data/aether/loot_tables/chests/dungeon/silver/silver_dungeon_reward.json
  src/main/java/com/aetherteam/aether/data/generators/loot/AetherDungeonLoot.java
Labels: status/pending-review

#1187 feat: Moa follow behavior
  src/main/java/com/aetherteam/aether/entity/ai/goal/MoaFollowGoal.java
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
Labels: status/pending-review

#1185 fix: Improved check for Aerbunny jump resets
  src/main/java/com/aetherteam/aether/entity/passive/Aerbunny.java
Labels: status/pending-review

#1182 fix: Replace %s in Valkyrie death message
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/Valkyrie.java
Labels: status/pending-review

#1180 fix: Correct Valkyrie Lance lore entry
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review

#1176 refactor: Tweak movement speed and upwards movement for armor abilities
  src/main/java/com/aetherteam/aether/item/combat/abilities/armor/NeptuneArmor.java
  src/main/java/com/aetherteam/aether/item/combat/abilities/armor/PhoenixArmor.java
  src/main/java/com/aetherteam/aether/mixin/mixins/common/LivingEntityMixin.java
  src/main/resources/aether.mixins.json
Labels: status/pending-review

#1243 fix: Neptune Armor can boost downwards swimming speed
  src/main/java/com/aetherteam/aether/item/combat/abilities/armor/NeptuneArmor.java
Labels: status/pending-review

#1235 feat: Cake recipe from Skyroot Milk Buckets
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/data/aether/advancements/recipes/food/skyroot_milk_bucket_cake.json
  src/generated/resources/data/aether/recipes/skyroot_milk_bucket_cake.json
  src/main/java/com/aetherteam/aether/data/generators/AetherRecipeData.java
Labels: status/pending-review

#1232 fix: Holystone now only drops for the correct tool if the block has hardness
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
  src/main/java/com/aetherteam/aether/event/listeners/abilities/ToolAbilityListener.java
  src/main/java/com/aetherteam/aether/item/tools/abilities/HolystoneTool.java
Labels: status/pending-review

#1233 fix: Toggle Visibility tooltip no longer gets stuck
  src/main/java/com/aetherteam/aether/client/gui/screen/inventory/AccessoriesScreen.java
Labels: status/pending-review

#1236 fix: Discs are set to mono
  src/main/resources/assets/aether/sounds/item/records/aether_tune.ogg
  src/main/resources/assets/aether/sounds/item/records/ascending_dawn.ogg
Labels: status/pending-review

#1247 fix: Ensure waterlogged property is checked for
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/SunSpirit.java
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/slider/Slider.java
Labels: status/pending-review

#1250 refactor: Allow items to fall out of Aether
  src/main/java/com/aetherteam/aether/event/hooks/DimensionHooks.java
Labels: status/pending-review

#1249 fix: Silver Dungeon aerclouds have double drops
  src/main/java/com/aetherteam/aether/world/structure/SilverDungeonStructure.java
Labels: status/pending-review

#1248 fix: Rotation on quicksoil without moving is capped
  src/main/java/com/aetherteam/aether/block/FrictionCapped.java
Labels: status/pending-review

#1261 fix: Mounts wont get stuck in minecarts
  src/main/java/com/aetherteam/aether/event/hooks/EntityHooks.java
Labels: status/pending-review

#1264 feat: subtitles.aether.entity.item.pickup
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review

#1258 fix: No more z-fighting on Valkyrie model
  src/main/java/com/aetherteam/aether/client/renderer/entity/model/ValkyrieModel.java
Labels: status/pending-review

#1252 fix: Aechor Plants no longer get launched by Gravitite Swords
  src/generated/resources/.cache/0fe122e549a2e3aeeca535edbc3649f31121d28e
  src/generated/resources/data/aether/tags/entity_types/unlaunchable.json
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherEntityTagData.java
  src/main/java/com/aetherteam/aether/entity/monster/AechorPlant.java
Labels: status/pending-review

#1251 feat: Biome localization entries
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
  src/main/java/com/aetherteam/aether/data/providers/AetherLanguageProvider.java
Labels: status/pending-review

#1255 fix: Swet no longer squishes with noAI
  src/main/java/com/aetherteam/aether/entity/monster/Swet.java
Labels: status/pending-review

#1267 fix: Mounts no longer stop midair on blue aercloud
  src/main/java/com/aetherteam/aether/block/natural/BlueAercloudBlock.java
  src/main/java/com/aetherteam/aether/event/hooks/EntityHooks.java
  src/main/java/com/aetherteam/aether/event/listeners/EntityListener.java
Labels: status/pending-review

#1265 fix: Properly sync mount step
  src/main/java/com/aetherteam/aether/entity/MountableMob.java
  src/main/java/com/aetherteam/aether/entity/passive/Aerwhale.java
  src/main/java/com/aetherteam/aether/network/AetherPacketHandler.java
  src/main/java/com/aetherteam/aether/network/packet/server/StepHeightPacket.java
Labels: status/pending-review

#1238 improv: Use Loot Modifiers for entity loot double drops
  src/generated/resources/.cache/8c612d57ec52f747b666a8d00c73628b9773ba1d
  src/generated/resources/data/aether/loot_modifiers/double_drops.json
  src/generated/resources/data/aether/loot_modifiers/pig_drops.json
  src/generated/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLootModifierData.java
  src/main/java/com/aetherteam/aether/item/combat/SkyrootSwordItem.java
  src/main/java/com/aetherteam/aether/item/combat/abilities/weapon/SkyrootWeapon.java
  src/main/java/com/aetherteam/aether/item/combat/loot/PigSlayerItem.java
  src/main/java/com/aetherteam/aether/loot/modifiers/AetherLootModifiers.java
  src/main/java/com/aetherteam/aether/loot/modifiers/DoubleDropsModifier.java
  src/main/java/com/aetherteam/aether/loot/modifiers/PigDropsModifier.java
Labels: status/pending-review

#1246 fix: Fix banner pattern render issues
  src/main/java/com/aetherteam/aether/client/AetherAtlases.java
  src/main/java/com/aetherteam/aether/client/AetherClient.java
Labels: status/pending-review

#1244 fix: Properly sync tool debuff config
  src/main/java/com/aetherteam/aether/AetherConfig.java
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
  src/main/java/com/aetherteam/aether/event/listeners/abilities/ToolAbilityListener.java
  src/main/java/com/aetherteam/aether/network/AetherPacketHandler.java
  src/main/java/com/aetherteam/aether/network/packet/client/ToolDebuffPacket.java
Labels: status/pending-review

#1253 improv: Utilize dismount_underwater and fall_damage_immune tags
  src/generated/resources/.cache/0fe122e549a2e3aeeca535edbc3649f31121d28e
  src/generated/resources/data/minecraft/tags/entity_types/dismounts_underwater.json
  src/generated/resources/data/minecraft/tags/entity_types/fall_damage_immune.json
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherEntityTagData.java
  src/main/java/com/aetherteam/aether/entity/monster/Cockatrice.java
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/AbstractValkyrie.java
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/slider/Slider.java
  src/main/java/com/aetherteam/aether/entity/passive/Aerbunny.java
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
  src/main/java/com/aetherteam/aether/entity/passive/WingedAnimal.java
Labels: status/pending-review

#1256 fix: Moas restore jumps on blue aerclouds
  src/main/java/com/aetherteam/aether/entity/passive/Aerbunny.java
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
  src/main/java/com/aetherteam/aether/util/EntityUtil.java
Labels: status/pending-review
