Repository The-Aether-Team/The-Aether, pull requests merged in 2023-06, with the labels that each got.

#1473 refactor: Update translations
  src/main/resources/assets/aether/lang/ja_jp.json
  src/main/resources/assets/aether/lang/pl_pl.json
  src/main/resources/packs/classic_b173/assets/aether/lang/ja_jp.json
Labels: status/pending-review

#1496 fix: The slider doesn't emit walking sounds
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/slider/Slider.java
Labels: status/pending-review, feat/entity

#1497 fix: Bronze dungeons no longer generate far away from their structure chunk
  src/main/java/com/aetherteam/aether/world/structure/BronzeDungeonStructure.java
Labels: status/pending-review, feat/world-gen

#1494 fix: Chests should no longer break during generation in silver dungeons
  src/main/java/com/aetherteam/aether/world/structurepiece/silverdungeon/SilverDungeonRoom.java
  src/main/resources/data/aether/structures/silver_dungeon/chest_room.nbt
Labels: status/pending-review, feat/world-gen

#1508 build: Forge 45.0.47 -> 45.1.0
  gradle.properties
Labels: status/pending-review

#1513 feat: Missing Skyroot Wood entry and fixed other wood entries
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review

#1512 refactor: Allow Presents to be silk touched
  src/generated/resources/.cache/59eb3dbb5f86130e09b3c62d89b9525ee01cf52d
  src/generated/resources/data/aether/loot_tables/blocks/present.json
  src/main/java/com/aetherteam/aether/data/providers/AetherBlockLootSubProvider.java
Labels: status/pending-review

#1503 fix: Only living entities should detect Aerclouds as ground
  src/main/java/com/aetherteam/aether/block/natural/AercloudBlock.java
  src/main/java/com/aetherteam/aether/block/natural/BlueAercloudBlock.java
Labels: status/pending-review

#1499 improv: Bone Meal can now grow more Aether flowers
  src/generated/resources/.cache/103d9f3f36b01595f1aa5172191e60eff02e6924
  src/generated/resources/data/aether/worldgen/configured_feature/berry_bush_patch.json
  src/main/java/com/aetherteam/aether/block/natural/AetherGrassBlock.java
  src/main/java/com/aetherteam/aether/data/resources/registries/AetherConfiguredFeatures.java
Labels: status/pending-review

#1501 improv: Better Moa hitbox
  src/main/java/com/aetherteam/aether/entity/AetherEntityTypes.java
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
Labels: status/pending-review

#1500 refactor: Disable Golden Feather by default
  src/main/java/com/aetherteam/aether/AetherConfig.java
  src/main/java/com/aetherteam/aether/item/AetherCreativeTabs.java
Labels: status/pending-review

#1505 fix: Better setting for slow falling fallDistance
  src/main/java/com/aetherteam/aether/entity/miscellaneous/Parachute.java
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
  src/main/java/com/aetherteam/aether/entity/passive/Sheepuff.java
  src/main/java/com/aetherteam/aether/entity/passive/WingedAnimal.java
  src/main/java/com/aetherteam/aether/item/accessories/abilities/SlowFallAccessory.java
Labels: status/pending-review

#1502 fix: More animations stop when paused
  src/main/java/com/aetherteam/aether/client/renderer/entity/SliderRenderer.java
  src/main/java/com/aetherteam/aether/client/renderer/entity/model/QuadrupedWingsModel.java
Labels: status/pending-review

#1507 fix: Tool debuff config issues
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
Labels: status/pending-review

#1506 improv: Multidirectional model for PillarTop
  src/generated/resources/.cache/1742123cf955ee7ecf092ba55decb836aa65bc2c
  src/generated/resources/assets/aether/blockstates/pillar_top.json
  src/main/java/com/aetherteam/aether/block/AetherBlocks.java
  src/main/java/com/aetherteam/aether/block/miscellaneous/FacingPillarBlock.java
  src/main/java/com/aetherteam/aether/data/providers/AetherBlockStateProvider.java
Labels: status/pending-review

#1514 fix: Issue with falling when flying
  src/main/java/com/aetherteam/aether/event/hooks/DimensionHooks.java
Labels: status/pending-review

#1516 fix: Some aether recipes are no longer in the mc directory
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/data/aether/advancements/recipes/combat/blue_cape_blue_wool.json
  src/generated/resources/data/aether/advancements/recipes/combat/blue_cape_cyan_wool.json
  src/generated/resources/data/aether/advancements/recipes/combat/blue_cape_light_blue_wool.json
  src/generated/resources/data/aether/advancements/recipes/combat/netherite_gloves_smithing.json
  src/generated/resources/data/aether/advancements/recipes/combat/old_netherite_gloves_smithing.json
  src/generated/resources/data/aether/advancements/recipes/misc/aether_gold_nugget_from_blasting.json
  src/generated/resources/data/aether/advancements/recipes/misc/aether_gold_nugget_from_smelting.json
  src/generated/resources/data/aether/advancements/recipes/misc/aether_iron_nugget_from_blasting.json
  src/generated/resources/data/aether/advancements/recipes/misc/aether_iron_nugget_from_smelting.json
  src/generated/resources/data/aether/recipes/aether_gold_nugget_from_blasting.json
  src/generated/resources/data/aether/recipes/aether_gold_nugget_from_smelting.json
  src/generated/resources/data/aether/recipes/aether_iron_nugget_from_blasting.json
  src/generated/resources/data/aether/recipes/aether_iron_nugget_from_smelting.json
  src/generated/resources/data/aether/recipes/blue_cape_blue_wool.json
  src/generated/resources/data/aether/recipes/blue_cape_cyan_wool.json
  src/generated/resources/data/aether/recipes/blue_cape_light_blue_wool.json
  src/generated/resources/data/aether/recipes/netherite_gloves_smithing.json
  src/generated/resources/data/aether/recipes/old_netherite_gloves_smithing.json
  src/main/java/com/aetherteam/aether/data/generators/AetherRecipeData.java
Labels: status/pending-review

#1522 fix: Correct Flying Cow health
  src/main/java/com/aetherteam/aether/entity/passive/FlyingCow.java
Labels: status/pending-review

#1523 fix: Hammer projectile following momentum
  src/main/java/com/aetherteam/aether/entity/projectile/weapon/HammerProjectile.java
  src/main/java/com/aetherteam/aether/item/combat/loot/HammerOfKingbdogzItem.java
Labels: status/pending-review

#1521 refactor: Update Golden Gummy Swet and Golden Parachute texture colors
  src/main/resources/assets/aether/textures/item/food/golden_gummy_swet.png
  src/main/resources/assets/aether/textures/item/miscellaneous/golden_parachute.png
Labels: status/pending-review

#1527 fix: Projectiles shot by the wearer of the Shield of Repulsion no longer are affected by the shield
  src/main/java/com/aetherteam/aether/item/accessories/abilities/ShieldOfRepulsionAccessory.java
Labels: status/pending-review

#1528 refactor: More capitalization fixes
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review

#1532 refactor: Match Cockatrice hitbox with Moa hitbox
  src/main/java/com/aetherteam/aether/entity/AetherEntityTypes.java
Labels: status/pending-review

#1533 refactor: Improved Moa targetting
  src/main/java/com/aetherteam/aether/entity/passive/Moa.java
Labels: status/pending-review

#1539 fix: ItemUseConvertEvent running when it shouldn't
  src/main/java/com/aetherteam/aether/item/materials/behavior/ItemUseConversion.java
  src/main/java/com/aetherteam/aether/recipe/recipes/block/AmbrosiumRecipe.java
  src/main/java/com/aetherteam/aether/recipe/recipes/block/MatchEventRecipe.java
  src/main/java/com/aetherteam/aether/recipe/recipes/block/SwetBallRecipe.java
Labels: status/pending-review

#1541 improv: Fix Valkyrie Armor clipping exploit and also wing animation
  src/main/java/com/aetherteam/aether/capability/player/AetherPlayer.java
  src/main/java/com/aetherteam/aether/capability/player/AetherPlayerCapability.java
  src/main/java/com/aetherteam/aether/client/renderer/player/layer/PlayerWingsLayer.java
  src/main/java/com/aetherteam/aether/item/combat/abilities/armor/ValkyrieArmor.java
Labels: status/pending-review

#1544 feat: Holystone Generator
  src/main/java/com/aetherteam/aether/Aether.java
  src/main/java/com/aetherteam/aether/block/AetherBlocks.java
Labels: status/pending-review

#1538 feat: Key to toggle invisibility
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/capability/player/AetherPlayer.java
  src/main/java/com/aetherteam/aether/capability/player/AetherPlayerCapability.java
  src/main/java/com/aetherteam/aether/client/AetherKeys.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
  src/main/java/com/aetherteam/aether/item/accessories/cape/InvisibilityCloakItem.java
Labels: status/pending-review

#1550 improv: Fix multiplayer crash with invisibility toggle
  src/main/java/com/aetherteam/aether/capability/player/AetherPlayerCapability.java
  src/main/java/com/aetherteam/aether/item/accessories/cape/InvisibilityCloakItem.java
  src/main/java/com/aetherteam/aether/network/AetherPacketHandler.java
  src/main/java/com/aetherteam/aether/network/packet/server/InvisibilityTogglePacket.java
Labels: status/pending-review

#1554 fix: Correct tags in #aether:accessories
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherItemTagData.java
Labels: status/pending-review
