Repository The-Aether-Team/The-Aether, pull requests merged in 2023-09, with the labels that each got.

#1657 refactor: Tool debuff rebalancing
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
Labels: status/pending-review

#1671 improv: Tag-driven dungeon tooltips
  src/generated/resources/.cache/232d7dc54f63e89526c247ba29265b5afad0215c
  src/generated/resources/data/aether/tags/items/bronze_dungeon_loot.json
  src/generated/resources/data/aether/tags/items/gold_dungeon_loot.json
  src/generated/resources/data/aether/tags/items/silver_dungeon_loot.json
  src/main/java/com/aetherteam/aether/AetherTags.java
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherItemTagData.java
  src/main/java/com/aetherteam/aether/event/hooks/ItemHooks.java
  src/main/java/com/aetherteam/aether/event/listeners/ItemListener.java
  src/main/java/com/aetherteam/aether/item/AetherItems.java
  src/main/java/com/aetherteam/aether/item/accessories/AccessoryItem.java
  src/main/java/com/aetherteam/aether/item/combat/AetherArmorItem.java
  src/main/java/com/aetherteam/aether/item/combat/AetherSwordItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/CloudStaffItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/FlamingSwordItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/HammerOfKingbdogzItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/HolySwordItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/LightningKnifeItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/LightningSwordItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/PhoenixBowItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/PigSlayerItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/ValkyrieLanceItem.java
  src/main/java/com/aetherteam/aether/item/combat/loot/VampireBladeItem.java
  src/main/java/com/aetherteam/aether/item/food/GummySwetItem.java
  src/main/java/com/aetherteam/aether/item/miscellaneous/AetherRecordItem.java
  src/main/java/com/aetherteam/aether/item/miscellaneous/LifeShardItem.java
  src/main/java/com/aetherteam/aether/item/tools/valkyrie/ValkyrieAxeItem.java
  src/main/java/com/aetherteam/aether/item/tools/valkyrie/ValkyrieHoeItem.java
  src/main/java/com/aetherteam/aether/item/tools/valkyrie/ValkyriePickaxeItem.java
  src/main/java/com/aetherteam/aether/item/tools/valkyrie/ValkyrieShovelItem.java
Labels: status/pending-review

#1672 fix: Don't store dungeon overlay atlas sprites as static.
  src/main/java/com/aetherteam/aether/client/event/hooks/LevelClientHooks.java
Labels: status/pending-review

#1673 improv: Allow control over whether a Swet can spawn splash particles
  src/main/java/com/aetherteam/aether/entity/monster/Swet.java
Labels: status/pending-review

#1675 feat: GLM for randomly replacing armor with gloves in vanilla loot
  src/generated/resources/.cache/8c612d57ec52f747b666a8d00c73628b9773ba1d
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_chain.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_diamond.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_gold.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_iron.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_leather.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_netherite.json
  src/generated/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLootModifierData.java
  src/main/java/com/aetherteam/aether/loot/modifiers/AetherLootModifiers.java
  src/main/java/com/aetherteam/aether/loot/modifiers/GlovesLootModifier.java
Labels: status/pending-review

#1652 feat: Glowstone Ruined Portals
  src/generated/resources/.cache/103d9f3f36b01595f1aa5172191e60eff02e6924
  src/generated/resources/.cache/22b50738883487d1ef1961d9e5ff26fe1c21b339
  src/generated/resources/.cache/59eb3dbb5f86130e09b3c62d89b9525ee01cf52d
  src/generated/resources/.cache/8c612d57ec52f747b666a8d00c73628b9773ba1d
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/.cache/feecd04c25d277e5de10185e187a010c8d7228ee
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/data/aether/loot_modifiers/gloves_loot_iron.json
  src/generated/resources/data/aether/loot_tables/chests/ruined_portal.json
  src/generated/resources/data/aether/tags/blocks/non_ruined_portal_spawnable.json
  src/generated/resources/data/aether/tags/blocks/ruined_portal_ground_replaceable.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_aether.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_desert.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_jungle.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_mountain.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_standard.json
  src/generated/resources/data/aether/tags/worldgen/biome/has_ruined_portal_swamp.json
  src/main/java/com/aetherteam/aether/Aether.java
  src/main/java/com/aetherteam/aether/AetherConfig.java
  src/main/java/com/aetherteam/aether/AetherTags.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLootModifierData.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLootTableData.java
  src/main/java/com/aetherteam/aether/data/generators/loot/AetherChestLoot.java
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherBiomeTagData.java
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherBlockTagData.java
  src/main/java/com/aetherteam/aether/loot/AetherLoot.java
  src/main/java/com/aetherteam/aether/world/processor/AetherStructureProcessors.java
  src/main/java/com/aetherteam/aether/world/processor/GlowstonePortalAgeProcessor.java
  src/main/java/com/aetherteam/aether/world/processor/HolystoneReplaceProcessor.java
  src/main/java/com/aetherteam/aether/world/structure/AetherStructureTypes.java
  src/main/java/com/aetherteam/aether/world/structure/GlowstoneRuinedPortalStructure.java
  src/main/java/com/aetherteam/aether/world/structurepiece/AetherStructurePieceTypes.java
  src/main/java/com/aetherteam/aether/world/structurepiece/GlowstoneRuinedPortalPiece.java
  src/main/resources/data/aether/structures/ruined_portal/giant_portal_1.nbt
  src/main/resources/data/aether/structures/ruined_portal/giant_portal_2.nbt
  src/main/resources/data/aether/structures/ruined_portal/giant_portal_3.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_1.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_10.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_2.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_3.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_4.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_5.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_6.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_7.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_8.nbt
  src/main/resources/data/aether/structures/ruined_portal/portal_9.nbt
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal_aether.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal_desert.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal_jungle.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal_mountain.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure/ruined_portal_swamp.json
  src/main/resources/packs/ruined_portal/data/aether/worldgen/structure_set/ruined_portals.json
  src/main/resources/packs/ruined_portal/pack.png
Labels: status/pending-review

#1677 chore: beta.6 changelog
  docs/CHANGELOG.md
Labels: status/pending-review

#1683 refactor: Order Neptune Armor before Valkyrie Armor
  src/main/java/com/aetherteam/aether/item/AetherCreativeTabs.java
Labels: status/pending-review

#1686 improv: Hoppers no longer affect locked treasure chests
  src/main/java/com/aetherteam/aether/blockentity/TreasureChestBlockEntity.java
Labels: status/pending-review

#1691 fix: Fire Crystals move again
  src/main/java/com/aetherteam/aether/entity/projectile/crystal/FireCrystal.java
Labels: status/pending-review

#1692 fix: PVP config works correctly again
  src/main/java/com/aetherteam/aether/item/accessories/cape/InvisibilityCloakItem.java
Labels: status/pending-review

#1701 refactor: Egg advancement tag and skyroot bed crafting tag
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/.cache/e5c5eb35b4ba40351ecb7d9f04c3527f2f5779b0
  src/generated/resources/data/aether/advancements/obtain_egg.json
  src/generated/resources/data/aether/recipes/skyroot_bed.json
  src/main/java/com/aetherteam/aether/data/generators/AetherAdvancementData.java
  src/main/java/com/aetherteam/aether/data/generators/AetherRecipeData.java
Labels: status/pending-review

#1702 improv: Gloves now use ArmorMaterials
  src/main/java/com/aetherteam/aether/item/AetherItems.java
  src/main/java/com/aetherteam/aether/item/accessories/gloves/GlovesItem.java
  src/main/java/com/aetherteam/aether/item/accessories/gloves/GoldGlovesItem.java
  src/main/java/com/aetherteam/aether/item/accessories/gloves/LeatherGlovesItem.java
  src/main/java/com/aetherteam/aether/item/accessories/gloves/ZaniteGlovesItem.java
Labels: status/pending-review

#1704 refactor: Moa UV map expanded
  src/main/java/com/aetherteam/aether/client/renderer/entity/model/BipedBirdModel.java
  src/main/resources/assets/aether/textures/entity/mobs/cockatrice/cockatrice.png
  src/main/resources/assets/aether/textures/entity/mobs/cockatrice/cockatrice_emissive.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/black_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/blue_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/classic_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/mos.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/raptor.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/arctic_moa/arctic_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/boko_yellow/boko_yellow.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/boko_yellow/boko_yellow_saddle.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/cockatrice_moa/cockatrice_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/cockatrice_moa/cockatrice_moa_emissive.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/crookjaw_purple/crookjaw_purple.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/crookjaw_purple/crookjaw_purple_emissive.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/gharrix_red/gharrix_red.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/halcian_pink/halcian_pink.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/phoenix_moa/phoenix_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/phoenix_moa/phoenix_moa_emissive.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/sentry_moa/sentry_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/sentry_moa/sentry_moa_emissive.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/tivalier_green/tivalier_green.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/valkyrie_moa/valkyrie_moa.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/skins/valkyrie_moa/valkyrie_moa_saddle.png
  src/main/resources/assets/aether/textures/entity/mobs/moa/white_moa.png
Labels: status/pending-review, feat/art

#1719 fix: Aether Menu Music properly plays
  gradle.properties
  src/main/java/com/aetherteam/aether/client/gui/screen/menu/AetherTitleScreen.java
Labels: status/pending-review

#1718 improv: Server no longer stalls when spawning an entity with accessories
  src/main/java/com/aetherteam/aether/event/hooks/EntityHooks.java
  src/main/java/com/aetherteam/aether/event/listeners/EntityListener.java
  src/main/java/com/aetherteam/aether/mixin/mixins/common/ArmorStandMixin.java
  src/main/java/com/aetherteam/aether/mixin/mixins/common/ForgeEventFactoryMixin.java
  src/main/resources/aether.mixins.json
Labels: status/pending-review

#1712 improv: Queen dialogue screen no longer appears for multiple players
  src/main/java/com/aetherteam/aether/entity/monster/dungeon/boss/ValkyrieQueen.java
  src/main/java/com/aetherteam/aether/network/AetherPacketHandler.java
  src/main/java/com/aetherteam/aether/network/packet/clientbound/QueenDialoguePacket.java
Labels: status/pending-review

#1709 feat: Golden Amber trim material
  src/generated/resources/.cache/103d9f3f36b01595f1aa5172191e60eff02e6924
  src/generated/resources/.cache/232d7dc54f63e89526c247ba29265b5afad0215c
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/generated/resources/data/aether/trim_material/golden_amber.json
  src/generated/resources/data/minecraft/tags/items/trim_materials.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
  src/main/java/com/aetherteam/aether/data/generators/tags/AetherItemTagData.java
  src/main/java/com/aetherteam/aether/data/resources/registries/AetherTrimMaterials.java
  src/main/resources/assets/aether/textures/trims/color_palettes/golden_amber.png
  src/main/resources/assets/minecraft/atlases/armor_trims.json
Labels: status/pending-review

#1720 feat: Config for repositioning ascending text
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/AetherConfig.java
  src/main/java/com/aetherteam/aether/client/event/hooks/GuiHooks.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review

#1723 improv: Invisibility no longer desyncs on server
  src/main/java/com/aetherteam/aether/item/accessories/cape/InvisibilityCloakItem.java
  src/main/java/com/aetherteam/aether/network/AetherPacketHandler.java
  src/main/java/com/aetherteam/aether/network/packet/clientbound/SetInvisibilityPacket.java
Labels: status/pending-review

#1725 fix: Don't use level random
  src/main/java/com/aetherteam/aether/event/hooks/EntityHooks.java
Labels: status/pending-review, version/1.20.1

#1728 fix: Only set music to null after no longer active
  src/main/java/com/aetherteam/aether/client/AetherMusicManager.java
Labels: status/pending-review, version/1.19.4

#1732 fix: Remove JEI text shadows
  gradle.properties
  src/main/java/com/aetherteam/aether/integration/jei/categories/item/AbstractAetherCookingRecipeCategory.java
Labels: status/pending-review

#1738 fix: Cold lightmap works again
  src/main/java/com/aetherteam/aether/client/renderer/level/AetherSkyRenderEffects.java
Labels: status/pending-review

#1747 feat: Server Button
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/AetherConfig.java
  src/main/java/com/aetherteam/aether/client/gui/component/menu/AetherMenuButton.java
  src/main/java/com/aetherteam/aether/client/gui/screen/menu/AetherTitleScreen.java
  src/main/java/com/aetherteam/aether/client/gui/screen/menu/TitleScreenBehavior.java
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
  src/main/java/com/aetherteam/aether/mixin/mixins/client/ClientPacketListenerMixin.java
  src/main/java/com/aetherteam/aether/mixin/mixins/client/PauseScreenMixin.java
  src/main/java/com/aetherteam/aether/mixin/mixins/client/accessor/TitleScreenAccessor.java
  src/main/resources/aether.mixins.json
Labels: status/pending-review

#1757 fix: missing mimic sound
  src/generated/resources/assets/aether/sounds.json
Labels: status/pending-review

#1759 fix: Get armor equipment slots properly
  src/main/java/com/aetherteam/aether/event/hooks/AbilityHooks.java
Labels: status/pending-review

#1760 refactor: Clean up SmithingScreenMixin
  gradle.properties
  src/main/java/com/aetherteam/aether/mixin/mixins/client/SmithingScreenMixin.java
Labels: status/pending-review

#1762 feat: Grindstone recipe w/ Holystone Slab
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/data/aether/advancements/recipes/decorations/skyroot_grindstone_holystone_slab.json
  src/generated/resources/data/aether/recipes/skyroot_grindstone_holystone_slab.json
  src/main/java/com/aetherteam/aether/data/generators/AetherRecipeData.java
Labels: status/pending-review

#1769 Update Moa saddle layer
  src/main/java/com/aetherteam/aether/client/renderer/entity/model/BipedBirdModel.java
Labels: status/pending-review

#1768 fix: Use english locale
  src/main/java/com/aetherteam/aether/loot/modifiers/GlovesLootModifier.java
Labels: status/pending-review

#1773 feat: Updated and additional lore entries
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/assets/aether/lang/en_us.json
  src/main/java/com/aetherteam/aether/data/generators/AetherLanguageData.java
Labels: status/pending-review, feat/copy
